### ISSUE TITLE
Boot problem on lux

### ISSUE THREAD

**Issue by axxx007xxxz** [Alberto97/android_kernel_motorola_msm8916#2]
This is the continuation of a discussion started on XDA: [post 1](https://forum.xda-developers.com/showpost.php?p=76058974&postcount=385), [post 2](https://forum.xda-developers.com/showpost.php?p=76113125&postcount=387) and [post 3](https://forum.xda-developers.com/showpost.php?p=76125160&postcount=388).

I've made a build with WLAN driver disabled [[commit 1](https://github.com/TeamHorizon/android_kernel_motorola_msm8916/commit/3cb1979348dc805396b52ecbeea41ef2f85fc29a) - [commit 2](https://github.com/TeamHorizon/android_device_motorola_msm8916-common/commit/ee6fccb08cbe7601516b12be8a84d93793f22111)] but it's still broken; I'm not entirely sure I did it the right way, but it should work.
Here's the log: https://hastebin.com/nikixezuda.scala.

Checking the log I've seen this error popping out a few times:
`[    0.277447,1] i2c-msm-v2 78ba000.i2c: probing driver i2c-msm-v2`
`[    0.277592,1] i2c-msm-v2 78ba000.i2c: error on clk_get(core_clk):-517`
`[    0.277610,1] i2c-msm-v2 78ba000.i2c: error probe() failed with err:-517`
however, it doesn't seem to be a fatal error since the boot process goes on.
I still can't pass the "unlocked bootloader" screen: it reaches the screen, it vibrates and just hangs there.

In case you have any other idea, please let me know and I'll try as soon as possible. Thanks!

**Comment by joelmaxuel** [comment]
Someone lucky to get a ramoops.  I am happy someone else is trying to tackle this, since I am getting same (sans ramoops).  
Did the Hastebin logs get taken down?  I don't see any content.

Maybe it's possible that the 32bit binder was already taken out of AOSP mianline, making "CONFIG_ANDROID_BINDER_IPC_32BIT=y" a problem.

EDIT: Okay, that was a dead end.  And still not experiencing any logs in pstore.

**Comment by axxx007xxxz** [comment]
@joelmaxuel: Oops, you're right. I'll restore the link as soon as possible.

**Comment by Alberto97** [comment]
Hmm there's audio stuff in the stack trace... try reverting b838028c4e356590ca9208bfd1fcea900c9bdd1b just to exclude any stupid mistake I might have made.

**Comment by joelmaxuel** [comment]
Just made a boot.img and fastboot booted that.  I don't know if brightness adjusted while vibrating before, but I noticed that this time.  
At any rate, three minutes in at splash screen though.  And still a zero-byte annotate-ramoops.
I will need to see what @axxx007xxxz is doing to get the ramoops (I did have them before when I had a different issue - like being on the MM bootloader cos I forgot to check for an official N update).

**Comment by Alberto97** [comment]
IIRC with "fastboot boot" dt changes aren't picked, you have to flash the boot image to apply them.

**Comment by axxx007xxxz** [comment]
Looks like the link works fine now.

@Alberto97: Thank you for the tip, I'll make a build with that commit reverted.

**Comment by axxx007xxxz** [comment]
@Alberto97: I've just made a build with the revert and now it doesn't even vibrate when it reaches the "unlocked bootloader" screen.
ramoops shows TWRP Kernel. I think it's because, since flash, it's the last Kernel that has booted.

**Comment by axxx007xxxz** [comment]
Side note: when I test these changes, I always make a full clean ROM build.

**Comment by DroidFreak32** [comment]
I can confirm that [surnia](https://github.com/oreo-surnia/android_kernel_motorola_msm8916/commits/lineage-15.1-alberto) is affected like lux too.

**Comment by Alberto97** [comment]
This is game changing, I did not expect issues on surnia and I can't see anything wrong anywhere.
Just to know, did the nougat rebased kernel work at a certain point in the past?
Also please make sure your ramdisk is free from device specific stuff (especially fstab.qcom).

**Comment by joelmaxuel** [comment]
I used the cm-14.1 kernel on lineage GitHub for Oreo 8.0, with a couple commits tacked on, and the biggest issue I had with that was camera (if kernel was causing that - I was on the MM bootloader back then too).
When I switched kernels for 8.1, was when I lost boot.  And I think I tried at one point for chuckles the 14.1 kernel, forgot how that turned out.

Current repos (for reference):
https://github.com/CarbonROM/android_device_motorola_lux/tree/cr-6.1
https://skynet.maxuel.tk:1443/AllOutOfLuxToGive/android_device_motorola_msm8916-common/commits/cr-6.1
This kernel and axxx007xxxz's vendor

**Comment by axxx007xxxz** [comment]
@Alberto97: I've never got this Kernel to boot, I remember I tried it some months ago.
I'll check the ramdisk thing.

**Comment by axxx007xxxz** [comment]
@Alberto97: "fstab.qcom" of compiled ROM is exactly the same of common tree's one, as you can see here: https://hastebin.com/wopegiguve.scala.
About ramdisk, lux only has "init_lux.cpp" which shouldn't affect boot: https://github.com/TeamHorizon/android_device_motorola_lux/tree/o-experimental/init.

**Comment by ghost** [comment]
I can confirm that it didn't boot on osprey. It didn't go past "your bootloader is unlocked" screen.

**Comment by axxx007xxxz** [comment]
@kioth: This is weird since @Alberto97's [AOSP ROM](https://forum.xda-developers.com/2015-moto-g/orig-development/rom-android-source-project-8-0-t3709129) uses this Kernel as far as I know.
Can you get the ramoops log?

**Comment by ghost** [comment]
@axxx007xxxz: I'll try to boot this kernel again in a couple of minutes and see if it produces ramoops. I am using Lineage OS 14.1, but that shouldn't affect it, right? Or does it only work on Oreo ROMs?

**Comment by joelmaxuel** [comment]
@kioth - Oreo ROMs were where we were facing the issue.  Not sure if anyone tried this kernel against an older Android version before now.

**Comment by kioth** [comment]
@axxx007xxxz: I just downloaded the latest AOSP ROM for osprey by Alberto and extracted boot.img file from it. The boot.img I compiled from the source code is 6.0MB and the one from AOSP ROM is 7.56MB. So they are very different.

**Comment by joelmaxuel** [comment]
Is probably a Nougat thing though.  Lux for Oreo is 7,747,584 bytes (7.39 MiB).  Although, I am now interested enough in a Osprey build for the latest CarbonROM.  I will see if I can make and privately post one late tonight.

**Comment by ghost** [comment]
@joelmaxuel so, are you saying I need to specify the ROM version when I'm compiling the kernel? I just downloaded and compiled it, I didn't specify which version of Android I'm going to use. I'm guessing it defaults to Oreo. How do I compile it for nougat?

I realized that boot.img file size is not a good indicator of differences between them but when I extract the boot.img files, AOSP kernel is 21.03 and my kernel is 21.02. So there's still a slight difference.

**Comment by joelmaxuel** [comment]
Not necessarily, I'm only supposing the ROM build adds stuff to the ramdisk that a kernel-only build, or ROM build for a different Android version, does not have.
I can very well be wrong on this since that theory does not make sense to me, but it is something I have heard (even indirectly in this thread).

**Comment by ghost** [comment]
@joelmaxuel: I don't understand what you said. I'll install AOSP ROM by Alberto and try to boot my kernel with it. It will answer my questions.

**Comment by ghost** [comment]
@axxx007xxxz: I got the ramoops log.

[log](https://hastebin.com/vicotahoti.cs)

Except the last 13 lines, all other lines were repeated 3 more times, as indicated by "critical process 'servicemanager' exited 4 times in 4 minutes". 

I also got the same error as yours. 
`[    0.153521,1] i2c-msm-v2 78b6000.i2c: probing driver i2c-msm-v2
[    0.153627,1] i2c-msm-v2 78b6000.i2c: error on clk_get(core_clk):-517
[    0.153644,1] i2c-msm-v2 78b6000.i2c: error probe() failed with err:-517
[    0.153669,1] platform 78b6000.i2c: Driver i2c-msm-v2 requests probe deferral`

**Comment by ghost** [comment]
It booted on Alberto's AOSP Oreo ROM. So I guess, I need to compile it for nougat to make it work with LOS 14.1. 
@Alberto97: hi, what do I need to do to make it boot on LOS 14.1? I'm sorry, I know you're not developing for LOS anymore but their kernel isn't as good as yours. Yours is also more up-to-date on CVE patches. My only problem with AOSP Oreo ROM is that its SELinux isn't in enforcing mode. Otherwise, it's a great ROM. 

Is it possible to add SELinux support for your AOSP ROM by copying SELinux rules from LOS 15.1 or is it still a lot of work?

**Comment by joelmaxuel** [comment]
@Alberto97 I think I may try an AOSP Lux build in the next week (my build server needs a bit of work first though) to rule out another possibility.  Are you doing anything special with the msm8916 HALs or elsewhere in the ROM?  IIRC AOSP 8916 HALs has a few important commits lacking there so I have been using the LOS ones up until now.  Or wait...is CAF used at all for Osprey?

**Comment by axxx007xxxz** [comment]
I've made a build of the only Kernel (built separately from the ROM) to figure out if it's a ROM side issue.
Here's the link of the [AnyKernel2](https://github.com/axxx007xxxz/ak2_motorola_msm8916-lux) zip: https://transfer.sh/14bZdp/Motorola%20MSM8916%20Oreo%20lux.zip.
Please, test it.

This is the list of the commands I've executed in order to make this build: https://hastebin.com/yarobilamo.bash.

**Comment by joelmaxuel** [comment]
After adding system_qcom, removing LOS-style power hints, and a few other adjustments I got AOSP 8.1.0r9 to build, but I got this fail at the bootloader after flashing: https://imgur.com/a/Y3Tn73F
I used the zImage in the ROM build (renamed as "kernel"), and tried a different zImage (from my in-line Carbon build) as well.  Unsure of what is going on.

Also, tried CarbonROM with your kernel flashed right after, stuck at the bootloader without any vibration @axxx007xxxz 

I did get a ramoops - quite garbled though: https://pastebin.com/4si4YXM2

**Comment by ghost** [comment]
Hi @Alberto97 Are you interested in Postmarket OS? I thought you might be interested in helping that project. I really care about security and I like to have up-to-date software on my phone, I'm sure you also care about it. I really wish we can use mainline kernel on our phones. I think Postmarket OS will make that dream happen. I am trying to boot your AOSP ROM using mainline kernel on my osprey. My goal is to use mainline kernel on my phone, OS doesn't matter. Since you are very experienced, you might be interested in making mainline boot. Mainlining kernel is one of the goals of PMOS. Here's the list of devices and what is working on them: https://wiki.postmarketos.org/index.php?title=Devices if you are interested, you can also make other features work as well. Thank you

**Comment by axxx007xxxz** [comment]
Please, stay in topic.

**Comment by ghost** [comment]
@axxx007xxxz sorry

**Comment by joelmaxuel** [comment]
I suppose if there was progress, it would be mentioned here.  So anyone still looking into this?  

I ended up building the kernel from scratch for anykernel and as well an AOSP build.  With AOSP I am still getting the image I posted on imgur for the April 29th post, including when I use with the anykernel flash.

When I flash anykernel after a carbon build (which by itself has the behaviour of vibrate, stall, no logs), the phone does not vibrate, stalls, and the ramoops is garbled.  So same behaviour as April 29th.

FWIW, my make param,s are:
`make O=../out ARCH=arm lux_defconfig`
`make O=../out ARCH=arm -j5 CROSS_COMPILE=../arm-linux-androideabi-4.9/bin/arm-linux-androideabi- VARIANT_DEFCONFIG=lux_defconfig`

**Comment by joelmaxuel** [comment]
@Alberto97, I tried the commits referenced some months back and still no joy.  Seems like the support for devices that use moto's msm8916 common board are dead now anyway (please correct me if I am wrong on this, especially when it comes to Pie although Oreo would be relevant too).
I would not be adverse to attempt an arm64 build at some point (my `lux` is available again for tinkering with), but because of the state of moto's msm8916 support, I have little hopes in getting anywhere much less getting `lux` to Pie.  
So I may as well cut my losses now and suggest this issue can at last be closed.  Many thanks to all your attention to this matter.

**Comment by Alberto97** [comment]
Referenced commits are unrelated. Github linked them here just because they contains "#2" in their commit message.
About moto8916 support I can only speak for myself and I stopped it the last December but I think Sultan still wants to work on these devices. Also I think he fixed this boot issue this way: moto8916/android_kernel_motorola_msm8916@a28b858dd7e12384c3c2753fe18004a4bf42bdec.
You might want to use that kernel directly since mine is out of date and no more maintained.
